language: python

cache:
  - ccache
  - pip

sudo: true

env:
    TOX_ENV=py27,py34,py35

install:
  - pip install -r requirements.txt

script:
  - isort -c
  - flake8
  - tox -e $TOX_ENV

notifications:
    email:
        - travis@joaojunior.org
